// Generated by scripts/generate-worktrunk-reference.ts from wt v0.75.0.
// Do not edit by hand.

export const WORKTRUNK_REFERENCE_VERSION = "wt v0.75.0";
export const WORKTRUNK_COMMANDS = ["switch","list","remove","merge","step","hook","config"] as const;

export const WORKTRUNK_REFERENCE = `Worktrunk command reference

Global options:
- -C <path>: Working directory for this command
- --config <path>: User config file path
- --config-set <toml>: Override config with inline TOML, e.g. --config-set list.full=true (repeatable)
- -v, --verbose...: Verbose output (-v: info logs + hook/alias template variables on stderr; -vv: also debug logs and raw subprocess output written to .git/wt/logs/). Set WORKTRUNK_VERBOSE=0|1|2 to apply the same level everywhere — including shell completion, which no flag can reach
- -y, --yes: Skip approval prompts

switch — Switch to a worktree; create if needed
Usage: wt switch [OPTIONS] [BRANCH] [-- <EXECUTE_ARGS>...]
Arguments:
- [BRANCH]: Branch, worktree path, shortcut, or PR/MR URL Opens interactive picker if omitted. Shortcuts: ^ (default branch), - (previous), @ (current), pr:{N} (GitHub PR), mr:{N} (GitLab MR)
- [EXECUTE_ARGS]...: Additional arguments for --execute command (after --) Arguments after -- are appended to the execute command. Each argument is expanded for templates, then POSIX shell-escaped.
Options:
- -c, --create: Create a new branch
- -b, --base <BASE>: Base branch Defaults to default branch. Supports the same shortcuts as the branch argument: ^, @, -, pr:{N}, mr:{N}.
- -x, --execute <EXECUTE>: Command to run after switch Replaces the wt process with the command after switching, giving it full terminal control. Useful for launching editors, AI agents, or other interactive tools.
- --clobber: Remove stale paths at target
- --no-cd: Skip directory change after switching Hooks still run normally. Useful when hooks handle navigation (e.g., tmux workflows) or for CI/automation. Use --cd to override.
- --branches: Include branches without worktrees
- --remotes: Include remote branches
- --prs: Include open PRs/MRs
- --no-hooks: Skip hooks
- --format <FORMAT>: Output format JSON prints structured result to stdout. Designed for tool integration (e.g., Claude Code WorktreeCreate hooks).
Examples:
- {"command":"switch","args":["feature-auth"]}
- {"command":"switch","args":["-"]}
- {"command":"switch","args":["--create","new-feature"]}

list — List worktrees and their status
Usage: wt list [OPTIONS]
Subcommands:
- statusline: Single-line status for the current worktree
Options:
- --format <FORMAT>: Output format [default: table]
- --branches: Include branches without worktrees
- --remotes: Include remote branches
- --full: Show CI status and LLM summaries
- --progressive: Show fast info immediately, update with slow info Displays local data (branches, paths, status) first, then updates with remote data (CI, upstream) as it arrives. Use --no-progressive to force buffered rendering. Auto-enabled for TTY.
Examples:
- {"command":"list","args":[]}
- {"command":"list","args":["--full"]}
- {"command":"list","args":["--branches","--full"]}

list statusline — Single-line status for the current worktree
Options:
- --format <FORMAT>: Output format Possible values:

remove — Remove worktree; delete branch if merged
Usage: wt remove [OPTIONS] [BRANCHES]...
Arguments:
- [BRANCHES]...: Branch name or worktree path [default: current]
Options:
- --no-delete-branch: Keep branch after removal
- -D, --force-delete: Delete unmerged branches
- --foreground: Run removal in foreground (block until complete)
- --reap: Kill processes started in the worktree [experimental] Before removal, terminate processes whose working directory is under the worktree — dev servers, watchers, language servers. Processes holding a controlling terminal (interactive shells, terminal editors) are left alone. Unix only.
- -f, --force: Force worktree removal Remove a dirty worktree, including staged, modified, and untracked files. Without this flag, removal fails if the worktree has any uncommitted changes.
- --no-hooks: Skip hooks
- --format <FORMAT>: Output format JSON prints structured result to stdout after removal completes.
Examples:
- {"command":"remove","args":[]}
- {"command":"remove","args":["feature-branch"]}
- {"command":"remove","args":["old-feature","another-branch"]}

merge — Merge current branch into the target branch
Usage: wt merge [OPTIONS] [TARGET]
Arguments:
- [TARGET]: Target branch Defaults to default branch.
Options:
- --no-squash: Skip commit squashing
- --no-commit: Skip commit and squash
- --no-rebase: Skip rebase; require the target to fast-forward to the resulting tip
- --no-remove: Keep worktree after merge
- --no-ff: Create a merge commit (no fast-forward)
- --stage <STAGE>: What to stage before committing [default: all] Possible values:
- --no-hooks: Skip hooks
- --format <FORMAT>: Output format JSON prints structured result to stdout after merge completes.
Examples:
- {"command":"merge","args":[]}
- {"command":"merge","args":["develop"]}
- {"command":"merge","args":["--no-remove"]}

step — Run individual operations
Usage: wt step [OPTIONS] <COMMAND>
Subcommands:
- commit: Stage and commit with LLM-generated message
- squash: Squash commits since branching
- rebase: Rebase onto target
- push: Fast-forward target to current branch
- diff: Show all changes since branching
- copy-ignored: Copy gitignored files to another worktree
- eval: [experimental] Evaluate a template expression
- for-each: [experimental] Run command in each worktree
- promote: [experimental] Swap a branch into the main worktree
- prune: [experimental] Remove worktrees merged into the default branch
- relocate: [experimental] Move worktrees to expected paths
- tether: [experimental] Run a command; kill its whole process tree when its worktree is removed
Examples:
- {"command":"step","args":["commit"]}
- {"command":"step","args":["squash"]}
- {"command":"step","args":["rebase"]}

step commit — Stage and commit with LLM-generated message
Options:
- -b, --branch <BRANCH>: Branch to operate on (defaults to current worktree)
- --stage <STAGE>: What to stage before committing [default: all] Possible values:
- --dry-run: Preview prompt, command, and generated message without committing
- --no-hooks: Skip hooks
- --format <FORMAT>: Output format JSON prints structured result to stdout after the commit completes.

step squash — Squash commits since branching
Arguments:
- [TARGET]: Target branch Defaults to default branch.
Options:
- --stage <STAGE>: What to stage before committing [default: all] Possible values:
- --dry-run: Preview prompt, command, and generated message without squashing
- --no-hooks: Skip hooks
- --format <FORMAT>: Output format JSON prints structured result to stdout after the squash completes.

step rebase — Rebase onto target
Arguments:
- [TARGET]: Target branch, tag, or commit Defaults to default branch.
Options:
- --format <FORMAT>: Output format JSON prints structured result to stdout after the rebase completes.
Examples:
- {"command":"step","args":["rebase"]}
- {"command":"step","args":["rebase","develop"]}
- {"command":"step","args":["rebase","v1.2.0"]}

step push — Fast-forward target to current branch
Arguments:
- [TARGET]: Target branch Defaults to default branch.
Options:
- --no-ff: Create a merge commit (no fast-forward)
- --format <FORMAT>: Output format JSON prints structured result to stdout after the push completes.
Examples:
- {"command":"step","args":["push"]}
- {"command":"step","args":["push","develop"]}
- {"command":"step","args":["push","--no-ff"]}

step diff — Show all changes since branching
Arguments:
- [TARGET]: Target branch Defaults to default branch.
- [EXTRA_ARGS]...: Extra arguments forwarded to git diff
Options:
- -b, --branch <BRANCH>: Branch to operate on (defaults to current worktree)

step copy-ignored — Copy gitignored files to another worktree
Options:
- --from <FROM>: Source worktree branch Defaults to main worktree.
- --to <TO>: Destination worktree branch Defaults to current worktree.
- --dry-run: Show what would be copied
- --force: Overwrite existing files in destination
- --require-include: Require .worktreeinclude to copy anything
- --format <FORMAT>: Output format JSON prints structured result to stdout after the copy completes.

step eval — [experimental] Evaluate a template expression
Arguments:
- <TEMPLATE>: Template expression to evaluate
Options:
- --format <FORMAT>: Output format JSON prints {name, template, result} to stdout instead of the bare result.
Examples:
- {"command":"step","args":["eval","{{ branch | hash_port }}"]}
- {"command":"step","args":["eval","{{ branch | hash_port }},{{ (\\"supabase-api-\\" ~ branch) | hash_port }}"]}
- {"command":"step","args":["eval","{{ branch | sanitize_db }}"]}

step for-each — [experimental] Run command in each worktree
Arguments:
- <ARGS>...: Command template (see --help for all variables)
Options:
- --format <FORMAT>: Output format [default: text]

step promote — [experimental] Swap a branch into the main worktree
Arguments:
- [BRANCH]: Branch to promote to main worktree Defaults to current branch, or default branch from main worktree.
Options:
- --format <FORMAT>: Output format JSON prints structured result to stdout after the promote completes. The mismatch warning still appears on stderr in JSON mode (safety signal).

step prune — [experimental] Remove worktrees merged into the default branch
Options:
- --dry-run: Show what would be removed
- --min-age <MIN_AGE>: Skip worktrees younger than this [default: 1d]
- --foreground: Run removal in foreground (block until complete)
- --format <FORMAT>: Output format [default: text]
Examples:
- {"command":"step","args":["prune","--dry-run"]}
- {"command":"step","args":["prune"]}

step relocate — [experimental] Move worktrees to expected paths
Arguments:
- [BRANCHES]...: Worktrees to relocate (defaults to all mismatched)
Options:
- --dry-run: Show what would be moved
- --commit: Commit uncommitted changes before relocating
- --clobber: Backup non-worktree paths at target locations Moves blocking paths to <path>.bak.<timestamp>. If that name is taken, counts up (…-2, …-3, …) to a free name.
- --format <FORMAT>: Output format JSON prints structured result to stdout after the relocate completes.
Examples:
- {"command":"step","args":["relocate","--dry-run"]}
- {"command":"step","args":["relocate"]}
- {"command":"step","args":["relocate","--commit","--clobber"]}

step tether — [experimental] Run a command; kill its whole process tree when its worktree is removed
Arguments:
- <COMMAND>...: Command to run (after --, run directly, no shell)

hook — Run configured hooks
Usage: wt hook [OPTIONS] <COMMAND>
Subcommands:
- show: Show configured hooks
- pre-switch: Run pre-switch hooks
- post-switch: Run post-switch hooks
- pre-start: Run pre-start hooks
- post-start: Run post-start hooks
- pre-commit: Run pre-commit hooks
- post-commit: Run post-commit hooks
- pre-merge: Run pre-merge hooks
- post-merge: Run post-merge hooks
- pre-remove: Run pre-remove hooks
- post-remove: Run post-remove hooks

hook show — Show configured hooks
Arguments:
- [HOOK_TYPE]: Hook type to show (default: all) [possible values: pre-switch, post-switch, pre-start, post-start, pre-commit, post-commit, pre-merge, post-merge, pre-remove, post-remove]
Options:
- --expanded: Show expanded commands with current variables
- --format <FORMAT>: Output format JSON prints structured result to stdout — one record per configured command.

hook pre-switch — Run pre-switch hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook post-switch — Run post-switch hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook pre-start — Run pre-start hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook post-start — Run post-start hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook pre-commit — Run pre-commit hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook post-commit — Run post-commit hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook pre-merge — Run pre-merge hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook post-merge — Run post-merge hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook pre-remove — Run pre-remove hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

hook post-remove — Run post-remove hooks
Arguments:
- [name]...: Filter by command name(s)
Options:
- --dry-run: Show what would run without executing
- --foreground: Run in foreground (block until complete)
- -y, --yes: Skip approval prompts for project hooks
- --var <KEY=VALUE>: Set template variable (deprecated — prefer --KEY=VALUE)

config — Manage user & project configs
Usage: wt config [OPTIONS] <COMMAND>
Subcommands:
- shell: Shell integration setup
- create: Create configuration file
- show: Show configuration files & locations
- update: Update deprecated config settings
- approvals: Manage command approvals
- alias: Inspect and preview aliases
- plugins: Plugin management
- state: Manage internal data and cache
Examples:
- {"command":"config","args":["shell","install"]}
- {"command":"config","args":["create"]}
- {"command":"config","args":["create","--project"]}

config shell — Shell integration setup
Subcommands:
- init: Generate shell integration code
- install: Write shell integration to config files
- uninstall: Remove shell integration from config files
- show-theme: Show output theme samples

config shell init — Generate shell integration code
Arguments:
- <bash|fish|nu|zsh|powershell>: Shell to generate code for [possible values: bash, fish, nu, zsh, powershell]
Options:
- --cmd <CMD>: Command name for shell integration (defaults to binary name) Use this to create shell integration for an alternate command name. For example, --cmd=git-wt creates a git-wt shell function instead of wt, useful on Windows where wt conflicts with Windows Terminal.

config shell install — Write shell integration to config files
Arguments:
- [bash|fish|nu|zsh|powershell]: Shell to install (default: all) [possible values: bash, fish, nu, zsh, powershell]
Options:
- --dry-run: Show what would be changed
- --cmd <CMD>: Command name for shell integration (defaults to binary name) Use this to create shell integration for an alternate command name. For example, --cmd=git-wt creates a git-wt shell function instead of wt, useful on Windows where wt conflicts with Windows Terminal.
Examples:
- {"command":"config","args":["shell","install"]}
- {"command":"config","args":["shell","install","zsh"]}

config shell uninstall — Remove shell integration from config files
Arguments:
- [bash|fish|nu|zsh|powershell]: Shell to uninstall (default: all) [possible values: bash, fish, nu, zsh, powershell]
Options:
- --dry-run: Show what would be changed
Examples:
- {"command":"config","args":["shell","uninstall"]}
- {"command":"config","args":["shell","uninstall","zsh"]}
- {"command":"config","args":["shell","uninstall","--yes"]}

config shell show-theme — Show output theme samples

config create — Create configuration file
Options:
- --project: Create project config (.config/wt.toml) instead of user config

config show — Show configuration files & locations
Options:
- --full: Run diagnostic checks (CI tools, commit generation, version)

config update — Update deprecated config settings
Options:
- --print: Print the migrated config to stdout instead of writing it
Examples:
- {"command":"config","args":["update"]}
- {"command":"config","args":["update","--yes"]}
- {"command":"config","args":["update","--print"]}

config approvals — Manage command approvals
Subcommands:
- list: List project commands and their approval status
- add: Store approvals in approvals.toml
- clear: Clear approved commands from approvals.toml
Examples:
- {"command":"config","args":["approvals","list"]}
- {"command":"config","args":["approvals","add"]}
- {"command":"config","args":["approvals","add","--yes"]}

config approvals list — List project commands and their approval status
Examples:
- {"command":"config","args":["approvals","list"]}

config approvals add — Store approvals in approvals.toml
Options:
- --all: Show all commands
Examples:
- {"command":"config","args":["approvals","add","--yes"]}

config approvals clear — Clear approved commands from approvals.toml
Options:
- -g, --global: Clear global approvals
- --stale: Clear only stale approvals

config alias — Inspect and preview aliases
Subcommands:
- show: Show an alias's template, or all aliases' templates
- dry-run: Preview an alias invocation with template expansion
Examples:
- {"command":"config","args":["alias","show"]}
- {"command":"config","args":["alias","show","deploy"]}
- {"command":"config","args":["alias","dry-run","deploy"]}

config alias show — Show an alias's template, or all aliases' templates
Arguments:
- [NAME]: Alias name (omit to show all)
Examples:
- {"command":"config","args":["alias","show"]}
- {"command":"config","args":["alias","show","deploy"]}

config alias dry-run — Preview an alias invocation with template expansion
Arguments:
- <NAME>: Alias name
- [ARGS]...: Arguments forwarded to the alias as if typed after wt <name>
Examples:
- {"command":"config","args":["alias","dry-run","deploy"]}
- {"command":"config","args":["alias","dry-run","deploy","--","staging","us-east-1"]}
- {"command":"config","args":["alias","dry-run","deploy","--","--env=staging"]}

config plugins — Plugin management
Subcommands:
- claude: Claude Code plugin
- codex: Codex plugin
- opencode: OpenCode plugin
Examples:
- {"command":"config","args":["plugins","claude","install"]}
- {"command":"config","args":["plugins","codex","install"]}
- {"command":"config","args":["plugins","opencode","install"]}

config plugins claude — Claude Code plugin
Subcommands:
- install: Install the Worktrunk plugin
- uninstall: Remove the Worktrunk plugin
- install-statusline: Configure the Claude Code statusline
Examples:
- {"command":"config","args":["plugins","claude","install"]}
- {"command":"config","args":["plugins","claude","uninstall"]}
- {"command":"config","args":["plugins","claude","install-statusline"]}

config plugins claude install — Install the Worktrunk plugin

config plugins claude uninstall — Remove the Worktrunk plugin

config plugins claude install-statusline — Configure the Claude Code statusline

config plugins codex — Codex plugin
Subcommands:
- install: Configure the Worktrunk marketplace in Codex
- uninstall: Remove the Worktrunk marketplace from Codex
Examples:
- {"command":"config","args":["plugins","codex","install"]}
- {"command":"config","args":["plugins","codex","uninstall"]}

config plugins codex install — Configure the Worktrunk marketplace in Codex

config plugins codex uninstall — Remove the Worktrunk marketplace from Codex

config plugins opencode — OpenCode plugin
Subcommands:
- install: Install the activity tracking plugin
- uninstall: Remove the activity tracking plugin
Examples:
- {"command":"config","args":["plugins","opencode","install"]}
- {"command":"config","args":["plugins","opencode","uninstall"]}

config plugins opencode install — Install the activity tracking plugin
Examples:
- {"command":"config","args":["plugins","opencode","install"]}
- {"command":"config","args":["plugins","opencode","install","--yes"]}

config plugins opencode uninstall — Remove the activity tracking plugin
Examples:
- {"command":"config","args":["plugins","opencode","uninstall"]}

config state — Manage internal data and cache
Subcommands:
- get: Get all stored state
- clear: Clear all stored state
- cache: Regenerable caches
- default-branch: Default branch detection and override
- logs: Operation and debug logs
- marker: Branch markers
- vars: [experimental] Custom variables per branch
Examples:
- {"command":"config","args":["state","default-branch"]}
- {"command":"config","args":["state","default-branch","set","main"]}
- {"command":"config","args":["state","marker","set","🚧"]}

config state get — Get all stored state
Options:
- --format <FORMAT>: Output format [default: table]

config state clear — Clear all stored state

config state cache — Regenerable caches
Subcommands:
- get: Show cache contents
- clear: Drop all caches
Examples:
- {"command":"config","args":["state","cache"]}
- {"command":"config","args":["state","cache","clear"]}

config state cache get — Show cache contents

config state cache clear — Drop all caches

config state default-branch — Default branch detection and override
Subcommands:
- get: Get the default branch
- set: Set the default branch
- clear: Clear the default branch cache

config state default-branch get — Get the default branch
Examples:
- {"command":"config","args":["state","default-branch"]}

config state default-branch set — Set the default branch
Arguments:
- <BRANCH>: Branch name to set as default
Examples:
- {"command":"config","args":["state","default-branch","set","main"]}

config state default-branch clear — Clear the default branch cache

config state logs — Operation and debug logs
Subcommands:
- get: List all log file paths
- profile: Performance profile from a trace
- clear: Clear all log files
Examples:
- {"command":"config","args":["state","logs"]}
- {"command":"config","args":["state","logs","clear"]}

config state logs get — List all log file paths
Examples:
- {"command":"config","args":["state","logs"]}

config state logs profile — Performance profile from a trace
Arguments:
- [FILE]: Trace to read (defaults to .git/wt/logs/trace.jsonl; - for stdin)
Examples:
- {"command":"list","args":["-vv"]}
- {"command":"config","args":["state","logs","profile"]}
- {"command":"config","args":["state","logs","profile","ci-run.jsonl"]}

config state logs clear — Clear all log files

config state marker — Branch markers
Subcommands:
- get: Get marker for a branch
- set: Set marker for a branch
- clear: Clear marker for a branch

config state marker get — Get marker for a branch
Options:
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","marker"]}
- {"command":"config","args":["state","marker","get","--branch=feature"]}

config state marker set — Set marker for a branch
Arguments:
- <VALUE>: Marker text (shown in wt list output)
Options:
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","marker","set","🚧"]}
- {"command":"config","args":["state","marker","set","✅ ready","--branch=feature"]}

config state marker clear — Clear marker for a branch
Options:
- --branch <BRANCH>: Target branch (defaults to current)
- --all: Clear all markers
Examples:
- {"command":"config","args":["state","marker","clear"]}
- {"command":"config","args":["state","marker","clear","--branch=feature"]}
- {"command":"config","args":["state","marker","clear","--all"]}

config state vars — [experimental] Custom variables per branch
Subcommands:
- get: Get a value
- list: List all keys
- set: Set a value
- clear: Clear a key or all keys
Examples:
- {"command":"config","args":["state","vars","set","env=staging"]}
- {"command":"config","args":["state","vars","get","env"]}
- {"command":"config","args":["state","vars","set","config={\\"port\\": 3000, \\"debug\\": true}"]}

config state vars get — Get a value
Arguments:
- <KEY>: Key name
Options:
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","vars","get","env"]}
- {"command":"config","args":["state","vars","get","env","--branch=feature"]}

config state vars list — List all keys
Options:
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","vars","list"]}
- {"command":"config","args":["state","vars","list","--branch=feature"]}

config state vars set — Set a value
Arguments:
- <KEY=VALUE>: KEY=VALUE pair
Options:
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","vars","set","env=staging"]}
- {"command":"config","args":["state","vars","set","config={\\"port\\": 3000}"]}
- {"command":"config","args":["state","vars","set","env=production","--branch=main"]}

config state vars clear — Clear a key or all keys
Arguments:
- [KEY]: Key to clear (required unless --all)
Options:
- --all: Clear all keys for the branch
- --branch <BRANCH>: Target branch (defaults to current)
Examples:
- {"command":"config","args":["state","vars","clear","env"]}
- {"command":"config","args":["state","vars","clear","--all"]}
- {"command":"config","args":["state","vars","clear","env","--branch=feature"]}`;
